### ISSUE TITLE
ical issue after upgrading to 2022.4

### ISSUE THREAD

**Issue by vingerha** [tybritten/ical-sensor-homeassistant#84]
Just  upgraded to 2022.4 and got below error. My only integration is a google calendar
```
Unable to prepare setup for platform ical.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).
```

**Comment by Olen** [comment]
See #82
