### ISSUE TITLE
Error since one week...

### ISSUE THREAD

**Issue by Seidel76** [tybritten/ical-sensor-homeassistant#82]
Since an update from core of Hassio, i've this error:

> 2022-03-31 09:57:14 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ical.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).
> 2022-03-31 09:57:14 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ical.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).
> 2022-03-31 09:57:14 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ical.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).

How can I resolve it please ?

**Comment by Olen** [comment]
This is related to this change in the core calendar component

https://github.com/home-assistant/core/pull/68724

**Comment by MMachor** [comment]
Is there a way around this?  Just updated to 2022.4.0 and it broke this integration with the same message.

**Comment by Olen** [comment]
@tybritten Do you mind taking a look at the two waiting PRs and making a new release if they are ok?
As of now, the integration does not work with 2022.4

**Comment by Olen** [comment]
Should be resolved in #83

**Comment by tybritten** [comment]
just released as 1.5.0 
https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/1.5.0

**Comment by MMachor** [comment]
Updated and working great again!  I use this for work to set automations for scheduled client meetings.  Thanks!
